import type { PageContent } from './types'

export const oms: PageContent = {
  meta: {
    route: '/oms',
    title: 'OMS: Outage Management System',
    subtitle: 'Outage, call, and continuity indicator management',
    navLabel: 'OMS',
    demoLabel: 'OMS',
  },
  blocks: [
    { kind: 'heading', level: 2, number: '7.1', text: 'Overview' },
    {
      kind: 'paragraph',
      text: 'SpinTech OMS (Outage Management System) is the specialized outage management module of the SpinTech ADMS platform. Natively integrated with the SCADA, the network electrical model, and the advanced DMS functions, it provides the Operations Centre with a unified view of outages, field crews, affected consumers, and regulatory continuity indicators.',
    },
    {
      kind: 'box',
      title: 'Implemented functionalities',
      items: [
        'Outage Scheduling Management: planned outage management;',
        'Trouble Call Management System (TCS): consumer call management;',
        'Crew Dispatch & Work Management: crew dispatching and work orders;',
        'Outage Analytics & Reporting: dashboards and analytical reports;',
        'Web Clients & Mobile Views: access via browser and mobile devices.',
      ],
    },
    {
      kind: 'paragraph',
      text: 'The OMS operates on a georeferenced electrical network model, correlating SCADA events, protection devices, consumer calls, operational records, and field activities to automatically determine the extent of the outage, the affected consumers, and the best restoration strategies.',
    },
    {
      kind: 'figure',
      src: 'oms-arquitetura-funcional.png',
      alt: 'SpinTech OMS functional architecture',
      caption: 'SpinTech OMS functional architecture',
    },

    { kind: 'heading', level: 2, number: '7.2', text: 'Outage Lifecycle' },
    {
      kind: 'paragraph',
      text: 'Each event recorded in the OMS goes through well-defined operational states, enabling real-time tracking from detection to closure.',
    },
    {
      kind: 'table',
      headers: ['State', 'Origin / Condition', 'Description'],
      rows: [
        [
          'Predictive',
          'Consumer calls via TCS',
          'Outage inferred from received calls; the probable fault area is propagated downstream of the protection device that operated.',
        ],
        [
          'Recognized',
          'Remote device opening via SCADA',
          'Automatically generated by the opening of a remotely controlled circuit breaker/recloser reported by the SCADA or confirmed by the DMS.',
        ],
        [
          'Restored',
          'All consumers restored',
          'The ticket is automatically closed by the OMS, which initiates the consumer callback process.',
        ],
        [
          'Completed',
          'Network returns to normal condition',
          'Complete resolution of the outage, with no remaining contingencies.',
        ],
        ['Cancelled', 'False alarm identified', 'The ticket was manually canceled by the operator after verification.'],
        ['Scheduled', 'Maintenance planning', 'Planned shutdown with prior notification to affected consumers.'],
      ],
    },
    { kind: 'heading', level: 3, number: '7.2.1', text: 'History Associated with Each Event' },
    {
      kind: 'boxgrid',
      columns: [
        {
          title: 'Operational Data',
          items: ['Time of occurrence', 'Equipment involved', 'Assigned crews', 'Cause of outage'],
        },
        {
          title: 'Impact Data',
          items: ['Affected consumers', 'Energy not supplied', 'Restoration time', 'Materials and operational costs'],
        },
      ],
    },

    { kind: 'heading', level: 2, number: '7.3', text: 'Outage Scheduling Management' },
    {
      kind: 'paragraph',
      text: 'The Planned Outage Management module enables planning and control of shutdowns required for maintenance, expansion or modernisation of the electrical network.',
    },
    {
      kind: 'boxgrid',
      columns: [
        {
          title: 'Module Functionalities',
          items: [
            'Registration of shutdown requests',
            'Request prioritization',
            'Issuance of work permits',
            'Operational planning',
            'Real-time status update',
            'Closure of work orders',
            'Prior notification to affected consumers',
          ],
        },
        {
          title: 'The Electrical Model Determines',
          items: [
            'Impacted consumers',
            'Affected transformers',
            'Interrupted loads',
            'Devices involved',
            'Projected continuity indicators',
          ],
        },
      ],
    },
    {
      kind: 'paragraph',
      text: 'The system also allows field crews to report delays, schedule changes, and updated power restoration forecasts, keeping operators and consumers continuously informed.',
    },

    { kind: 'heading', level: 2, number: '7.4', text: 'Trouble Call Management System (TCS)' },
    {
      kind: 'paragraph',
      text: 'The TCS manages consumer calls related to outages, acting as a correlation mechanism between field information, operational events, and registered complaints. Integrated with the geo-referenced electrical model, the SCADA, and corporate customer service systems.',
    },
    { kind: 'heading', level: 3, number: '7.4.1', text: 'Automatic Fault Location (Fault Locator)' },
    {
      kind: 'paragraph',
      text: 'Upon receiving a call, the system automatically identifies the customer unit, its geographic location, and its connection to the electrical grid. The incident is then linked to an existing event or used to create a new predictive outage - enabling the identification of faults not yet detected by remote-controlled devices.',
    },
    { kind: 'heading', level: 3, number: '7.4.2', text: 'Continuous Prediction Refinement' },
    {
      kind: 'paragraph',
      text: 'As new calls are registered, the system analyses the geographical distribution of affected consumers, the network topology, existing protection devices, and SCADA events, dynamically adjusting the probable fault area and the most likely outage point.',
    },
    { kind: 'heading', level: 3, number: '7.4.3', text: 'Call Categories' },
    {
      kind: 'table',
      headers: ['Category', 'Description'],
      rows: [
        ['Normal', 'Standard calls from residential and commercial consumers.'],
        ['Critical', 'Occurrences with significant operational impact or safety risk.'],
        ['Premium / VIP', 'Differentiated treatment for the utility’s strategic consumers.'],
        ['Medical', 'Consumers with special health needs who depend on electrical power.'],
      ],
    },
    { kind: 'heading', level: 3, number: '7.4.4', text: 'Call Lifecycle States' },
    {
      kind: 'boxgrid',
      columns: [
        { title: 'Opening', items: ['Unassigned', 'Assigned', 'Incident'] },
        { title: 'In Progress', items: ['Trouble Call', 'Outage'] },
        { title: 'Resolution', items: ['Completed', 'Rejected'] },
        { title: 'Closure', items: ['Closed'] },
      ],
    },
    { kind: 'heading', level: 3, number: '7.4.5', text: 'Integration and Service Channels' },
    {
      kind: 'box',
      title: 'Channels and systems integrated with the TCS',
      items: [
        'Utility Customer Service Centre (via Communication Server / SpinTech Edge);',
        'Contact Centre and IVR (Interactive Voice Response);',
        'Mobile applications and digital service channels;',
        'OPC interfaces, Web Services, and REST APIs for real-time updates.',
      ],
    },
    {
      kind: 'paragraph',
      text: 'This architecture enables automated call reception, automatic fault logging, incident status updates, and the communication of estimated restoration times, reducing the need for manual intervention.',
    },

    { kind: 'heading', level: 2, number: '7.5', text: 'Automatic Outage Prediction' },
    {
      kind: 'paragraph',
      text: 'When a supervised protection device operates due to a fault, the OMS automatically performs a downstream electrical analysis of the operated equipment (outage prediction), electrically traversing the downstream network to create outage tickets and reduce the time to identify the occurrence.',
    },
    {
      kind: 'boxgrid',
      columns: [
        {
          title: 'The System Determines',
          items: ['Impacted feeders', 'Affected transformers', 'Consumers without power', 'Probable fault area'],
        },
        {
          title: 'Automatic Closure',
          items: [
            'When the device returns to the normal state (automatically or by SCADA command), the ticket is closed and the communication and event closure procedures are initiated.',
          ],
        },
      ],
    },

    { kind: 'heading', level: 2, number: '7.6', text: 'Ticket and Event Management' },
    {
      kind: 'paragraph',
      text: 'All outage records are organized in a structured ticket system, with categorization, operational states, and flexible display options.',
    },
    { kind: 'heading', level: 3, number: '7.6.1', text: 'Available Display Filters' },
    {
      kind: 'box',
      title: 'Operators can filter tickets by',
      items: [
        'Electrical area, geographical region, or feeder;',
        'Responsible substation;',
        'Assigned crew;',
        'Call criticality.',
      ],
    },
    {
      kind: 'paragraph',
      text: 'All information is available in both tabular and interactive map formats, enabling simultaneous analysis of multiple occurrences.',
    },

    { kind: 'heading', level: 2, number: '7.7', text: 'Crew Dispatch & Work Management' },
    {
      kind: 'paragraph',
      text: 'The Crew Dispatch and Work Order Management module provides tools for complete management of field resources involved in system restoration.',
    },
    {
      kind: 'boxgrid',
      columns: [
        {
          title: 'Real-Time Monitoring',
          items: [
            'Crew locations',
            'Each crew’s workload',
            'Open work orders',
            'Activities in progress',
            'Restoration progress',
          ],
        },
        {
          title: 'Management Functionalities',
          items: [
            'Work order creation',
            'Automatic or manual crew assignment',
            'Execution monitoring',
            'Linking between orders and OMS events',
            'Operational closure of activities',
          ],
        },
      ],
    },
    {
      kind: 'paragraph',
      text: 'The operational interface features visual progress indicators that facilitate dispatchers’ decision-making in contingency situations.',
    },

    { kind: 'heading', level: 2, number: '7.8', text: 'AVL: Crew Location' },
    {
      kind: 'paragraph',
      text: 'The OMS incorporates AVL (Automatic Vehicle Location) functionality to monitor field crews’ locations on the operational map.',
    },
    {
      kind: 'table',
      headers: ['Information', 'Description'],
      rows: [
        ['Current location', 'Real-time geographical position of each field crew.'],
        ['Distance to occurrence', 'Calculated the distance between the crew and the fault point.'],
        ['Crew status', 'Available or busy with another activity.'],
        ['Travel time', 'Estimated time of arrival at the occurrence location.'],
        [
          'Automatic crew suggestion',
          'Together with the DMS and FLISR, the system can automatically suggest the crews closest to the fault.',
        ],
      ],
    },

    { kind: 'heading', level: 2, number: '7.9', text: 'Operational Event and Switching Management' },
    {
      kind: 'paragraph',
      text: 'The OMS fully records all switching operations associated with isolation and restoration processes, maintaining a detailed history of each event.',
    },
    {
      kind: 'boxgrid',
      columns: [
        {
          title: 'Automatically Recorded',
          items: [
            'Equipment operated',
            'Time of each switching operation',
            'Crews involved',
            'Resources employed',
            'Operational costs',
          ],
        },
        {
          title: 'Supplemented After Restoration',
          items: [
            'Labour used',
            'Materials consumed',
            'Operational observations',
            'Root cause of the outage',
          ],
        },
      ],
    },
    {
      kind: 'paragraph',
      text: 'This information feeds the analytical and regulatory modules of SpinTech OMS.',
    },

    { kind: 'heading', level: 2, number: '7.10', text: 'Continuity and Service Quality Indicators' },
    {
      kind: 'paragraph',
      text: 'SpinTech OMS automatically calculates the main regulatory supply continuity indicators at daily, weekly, monthly, and annual time granularities, segregating planned and unplanned outages.',
    },
    {
      kind: 'table',
      headers: ['Index', 'Name', 'Calculation Basis'],
      rows: [
        [
          'SAIDI',
          'System Average Interruption Duration Index',
          'Total duration of consumer outages ÷ total number of consumers',
        ],
        [
          'SAIFI',
          'System Average Interruption Frequency Index',
          'Total number of consumer outages ÷ total number of consumers',
        ],
        ['CAIDI', 'Customer Average Interruption Duration Index', 'Automatically calculated by the SAIDI ÷ SAIFI ratio'],
        [
          'MAIFI',
          'Momentary Average Interruption Frequency Index',
          'Momentary outages monitored separately via automatic filtering of Auto-Reclose events',
        ],
      ],
    },
    { kind: 'heading', level: 3, number: '7.10.1', text: 'Indicator Presentation Granularity' },
    {
      kind: 'box',
      title: 'Indicators can be viewed by',
      items: ['Feeder;', 'Substation;', 'Municipality and District;', 'Operational region;', 'Entire utility.'],
    },

    { kind: 'heading', level: 2, number: '7.11', text: 'Outage Analytics & Reporting' },
    {
      kind: 'paragraph',
      text: 'The analytical module provides real-time operational dashboards and a comprehensive set of configurable reports, with support for drill-down, dynamic filters, parameterized queries, export, and customizable charts.',
    },
    {
      kind: 'boxgrid',
      columns: [
        {
          title: 'Performance Reports',
          items: [
            'Outage history',
            'Cause analysis',
            'Reliability KPIs',
            'Operational efficiency KPIs',
            'Recurring faults',
            'Critical feeders',
            'Worst-performing equipment',
          ],
        },
        {
          title: 'Operational Reports',
          items: ['Crew utilisation', 'Closed cases', 'Planned outages', 'Device statistics'],
        },
      ],
    },

    { kind: 'heading', level: 2, number: '7.12', text: 'Web Clients and Mobile Applications' },
    {
      kind: 'paragraph',
      text: 'SpinTech OMS provides access via web clients and mobile applications without requiring local installation, covering both Operations Centre monitoring functions and field activities.',
    },
    {
      kind: 'boxgrid',
      columns: [
        {
          title: 'Operations Centre (Web)',
          items: [
            'Geographical network display',
            'Outage monitoring',
            'Alarm and event tracking',
            'Switching sequence management',
            'Operational dashboards',
            'Performance indicator queries',
          ],
        },
        {
          title: 'Field Crews (Mobile)',
          items: [
            'Arrival at site registration',
            'Activity progress updates',
            'Record of switching operations executed',
            'Work completion',
            'Record of materials used',
            'Restoration information',
          ],
        },
      ],
    },
    {
      kind: 'paragraph',
      text: 'Updates made by field crews are reflected in real time on the Operations Centre screens and in the OMS ticket status.',
    },

    { kind: 'heading', level: 2, number: '7.13', text: 'Integration with SCADA, DMS, and Customer Service' },
    {
      kind: 'paragraph',
      text: 'The OMS operates fully integrated with the other SpinTech ADMS modules and the utility’s corporate systems. Events originating from the SCADA automatically generate OMS tickets; calls received by customer service can trigger predictive events that are subsequently correlated with real electrical occurrences.',
    },
    {
      kind: 'table',
      headers: ['System / Module', 'Integration Type', 'Data Flow'],
      rows: [
        ['SpinTech SCADA', 'Native (internal API)', 'Protection and telecontrol events → automatic OMS tickets.'],
        [
          'SpinTech DMS / FLISR',
          'Native (internal API)',
          'Topology and electrical analysis → fault location and crew suggestion.',
        ],
        [
          'Customer Service',
          'Native (internal API) ↔ Communication Server (SpinTech Edge)',
          'OMS tickets ↔ occurrence status for the customer.',
        ],
        ['Contact Centre / IVR', 'Web Services / REST API', 'Automated calls ↔ ticket registration and updates.'],
        ['Commercial Systems', 'APIs and integration services', 'Consumer data, contracts, and commercial history.'],
      ],
    },

    { kind: 'heading', level: 2, text: 'System Screens' },
    {
      kind: 'figure',
      src: 'oms-janela-gestao-eventos.png',
      alt: 'Event management window',
      caption: 'Event management window',
    },
    {
      kind: 'figure',
      src: 'oms-relatorios-saidi-saifi.png',
      alt: 'SAIDI and SAIFI indicator reports',
      caption: 'SAIDI and SAIFI indicator reports',
    },
  ],
}
