import type { PageContent } from './types'

export const oms: PageContent = {
  meta: {
    route: '/oms',
    title: 'OMS: Outage Management System',
    subtitle: 'Outage, call, and continuity indicator management',
    navLabel: 'OMS',
  },
  blocks: [
    {
      kind: 'paragraph',
      text: 'GridQ OMS (Outage Management System) is the module responsible for the operational management of power supply interruptions in distribution systems. It offers the operations centre an integrated, real-time view of events that affect continuity of supply, acting as the main tool for identifying, recording, analysing, tracking, and restoring occurrences in the electrical network.',
    },
    {
      kind: 'paragraph',
      text: 'GridQ OMS is natively integrated with the network’s electrical model, with GridQ SCADA, and with the advanced functions of a GridQ DMS, correlating protection events, consumer calls, operational records, and field activities to automatically determine the extent of the outage, the affected consumers, and the best restoration strategies.',
    },

    { kind: 'heading', level: 2, text: 'Switching and Topology Monitoring' },
    {
      kind: 'paragraph',
      text: 'GridQ OMS continuously monitors switching operations performed on the network, whether executed remotely via GridQ SCADA or manually recorded by operators for non-remotely-controlled elements. Based on this information, the system automatically processes the network topology, identifies energized and de-energized areas, determines affected consumers, and records the corresponding outage events.',
    },
    {
      kind: 'figure',
      src: 'oms-arquitetura-funcional.png',
      alt: 'GridQ OMS functional architecture',
      caption: 'GridQ OMS functional architecture',
    },

    { kind: 'heading', level: 2, text: 'Outage Lifecycle' },
    {
      kind: 'paragraph',
      text: 'Each event recorded in GridQ OMS goes through well-defined operational states, enabling real-time tracking from detection to closure:',
    },
    {
      kind: 'list',
      items: [
        'Predictive: an outage inferred from received calls, with the probable fault area propagated downstream of the protection device that operated;',
        'Recognized: automatically generated by the opening of a remotely-controlled circuit breaker/recloser, reported by GridQ SCADA;',
        'Restored: when all consumers are restored, the ticket is closed automatically and the consumer callback process is initiated;',
        'Completed: complete resolution of the outage, with no remaining contingencies;',
        'Cancelled: when a false alarm is identified and the ticket is manually cancelled after verification;',
        'Scheduled: planned shutdown, with prior notification to affected consumers.',
      ],
    },
    {
      kind: 'paragraph',
      text: 'For each event, the system maintains a complete history with operational data (time of occurrence, equipment involved, assigned crews, cause of the outage) and impact data (affected consumers, energy not supplied, restoration time, materials, and operational costs).',
    },

    { kind: 'heading', level: 2, text: 'Scheduled Outage Management' },
    {
      kind: 'paragraph',
      text: 'The scheduled outage management module allows planning and controlling shutdowns needed for maintenance, expansion, or modernization of the electrical network, including registration of requests, prioritization, issuance of work permits, operational planning, real-time status updates, and prior notification to consumers. The electrical model is used to automatically determine impacted consumers, affected transformers, interrupted loads, and projected continuity indicators.',
    },

    { kind: 'heading', level: 2, text: 'Consumer Call Management (Trouble Call Management System, TCS)' },
    {
      kind: 'paragraph',
      text: 'The TCS manages consumer calls related to outages, acting as a correlation mechanism between field information, operational events, and registered complaints. Integrated with the georeferenced electrical model, GridQ SCADA, and corporate service systems, the TCS offers:',
    },
    {
      kind: 'list',
      items: [
        'Automatic fault location: upon receiving a call, the system automatically identifies the consumer unit, its geographic location, and its connection to the electrical network, linking the incident to an existing event or creating a new predictive event;',
        'Continuous prediction refinement: as new calls are registered, the system analyses the geographic distribution of affected consumers, the network topology, and protection devices, dynamically adjusting the probable fault area;',
        'Call categorization: normal, critical, premium/VIP, and medical (consumers dependent on electrical power for health reasons);',
        'Call lifecycle: from opening (unassigned, assigned, incident) to closure, passing through intermediate and resolution states;',
        'Integration with multiple channels: call centre, contact centre/IVR, mobile apps, and digital channels, via REST APIs and web services.',
      ],
    },

    { kind: 'heading', level: 2, text: 'Automatic Outage Prediction' },
    {
      kind: 'paragraph',
      text: 'When a supervised protection device operates due to a fault, the OMS automatically performs a downstream electrical analysis of the operated equipment, traversing the network to create outage tickets and reduce the time to identify the occurrence, determining impacted feeders, affected transformers, consumers without power, and the probable fault area. The ticket is automatically closed when the device returns to its normal state.',
    },

    { kind: 'heading', level: 2, text: 'Ticket and Event Management' },
    {
      kind: 'paragraph',
      text: 'All outage records are organized in a structured ticket system, with categorization, operational states, and flexible display options, allowing filtering by electrical area, geographic region, feeder, substation, assigned crew, or call criticality, with display in both tabular format and interactive maps.',
    },

    { kind: 'heading', level: 2, text: 'Field Crew Management' },
    {
      kind: 'paragraph',
      text: 'The OMS offers complete tools for managing field resources involved in restoration, including real-time monitoring of crew location, workload, open work orders, and restoration progress, in addition to work-order creation, automatic or manual crew assignment, and execution tracking.',
    },
    {
      kind: 'paragraph',
      text: 'The AVL (Automatic Vehicle Location) functionality allows crews to be located geographically in real time, calculating the distance to the occurrence, checking availability, and estimating arrival time, and can, together with the automatic restoration analytical functions, automatically suggest the crews closest to the fault.',
    },

    { kind: 'heading', level: 2, text: 'Operational Switching Records' },
    {
      kind: 'paragraph',
      text: 'The OMS fully records all switching operations associated with isolation and restoration processes, maintaining a detailed history of each event, equipment operated, time of each switching operation, crews involved, and resources employed, complemented after restoration with information on labour used, materials consumed, and the root cause of the outage.',
    },

    { kind: 'heading', level: 2, text: 'Continuity and Supply Quality Indicators' },
    {
      kind: 'paragraph',
      text: 'The OMS automatically calculates the main regulatory continuity indicators at daily, weekly, monthly, and annual granularities, segregating planned and unplanned outages:',
    },
    {
      kind: 'list',
      items: [
        'SAIDI (System Average Interruption Duration Index): total duration of outages divided by the total number of consumers;',
        'SAIFI (System Average Interruption Frequency Index): total number of outages divided by the total number of consumers;',
        'CAIDI (Customer Average Interruption Duration Index): calculated automatically from the SAIDI/SAIFI ratio;',
        'MAIFI (Momentary Average Interruption Frequency Index): momentary outages monitored separately via automatic filtering of automatic-reclosing events.',
      ],
    },
    {
      kind: 'paragraph',
      text: 'These indicators can be viewed by feeder, substation, municipality/district, operational region, or for the entire utility.',
    },

    { kind: 'heading', level: 2, text: 'Analytics and Reports' },
    {
      kind: 'paragraph',
      text: 'The analytical module offers real-time operational dashboards and a comprehensive set of configurable reports, with support for drill-down, dynamic filters, parameterized queries, and customizable charts, covering everything from outage history and cause analysis to reliability and operational-efficiency KPIs, critical feeders, and worst-performing equipment.',
    },

    { kind: 'heading', level: 2, text: 'Web and Mobile Access' },
    {
      kind: 'paragraph',
      text: 'The OMS provides access via web clients and mobile applications, with no need for local installation, covering both operations-centre monitoring functions (geographic network display, outage monitoring, switching-sequence management, dashboards) and field activities (arrival-on-site logging, progress updates, switching records, work completion, and materials used). Updates made by field crews are reflected in real time on the operations centre’s screens.',
    },

    { kind: 'heading', level: 2, text: 'Integration with Other Systems' },
    {
      kind: 'paragraph',
      text: 'GridQ OMS operates fully integrated with the platform’s other modules and the utility’s corporate systems: events originating in SCADA automatically generate tickets in GridQ OMS; calls received by customer service can trigger predictive events subsequently correlated with real electrical occurrences; and integration with the topology and fault-location analytical functions supports the suggestion of the closest crews.',
    },

    { kind: 'heading', level: 2, text: 'Demo Application' },
    {
      kind: 'paragraph',
      text: 'The SAIDI/SAIFI Indicators functionality is part of the GridQ OMS reporting module and is responsible for automatically consolidating power-supply continuity indicators from the events recorded by the system. The calculations are performed using occurrences stored in the operational history, allowing analyses across different levels of the electrical network and the generation of technical reports to track service quality.',
    },

    { kind: 'heading', level: 3, text: 'SAIDI/SAIFI Indicators' },
    {
      kind: 'paragraph',
      text: 'The GridQ OMS SAIDI/SAIFI Indicators module offers a complete platform for monitoring the continuity of power supply, allowing the network’s performance to be tracked through the main international reliability indicators.',
    },
    {
      kind: 'paragraph',
      text: 'The solution automatically consolidates the outages recorded by the system, classifying them as planned or unplanned, and calculates the indicators for different levels of the utility’s structure, from the entire project down to states, divisions, cities, substations, and individual feeders. Results can be queried over daily, weekly, or monthly periods, providing a historical and managerial view of the quality of service provided.',
    },
    { kind: 'paragraph', text: 'The system automatically calculates:' },
    {
      kind: 'list',
      items: [
        'SAIDI (System Average Interruption Duration Index): represents the average time each consumer was without power during the period analysed.',
        'SAIFI (System Average Interruption Frequency Index): represents the average number of outages experienced by each consumer.',
        'Indicators separated for planned (PLA) and unplanned (UNP) outages, in addition to total values.',
        'Total number of outages (FAIL_NO).',
        'Accumulated unavailability time (FAIL_DI).',
      ],
    },
    {
      kind: 'paragraph',
      text: 'This approach allows operators, managers, and engineering teams to continuously track the evolution of regulatory indicators, identify critical areas of the network, and direct actions to improve the reliability of the electrical system.',
    },

    { kind: 'heading', level: 3, text: 'Available Reports' },
    {
      kind: 'paragraph',
      text: 'The module offers several specialized reports that support both daily operations and management analyses.',
    },
    { kind: 'heading', level: 4, text: 'General SAIDI/SAIFI Report' },
    {
      kind: 'paragraph',
      text: 'Presents the consolidated indicators stored in the system’s historical database, allowing SAIDI and SAIFI values to be queried by period and by organizational level of the electrical network.',
    },
    { kind: 'heading', level: 4, text: 'Planned and Unplanned Outage Reports' },
    {
      kind: 'paragraph',
      text: 'Provide the detailed history of occurrences recorded by the OMS, separating scheduled interventions from interruptions caused by operational failures. These reports allow tracking of opening and restoration times, outage duration, and equipment involved.',
    },
    { kind: 'heading', level: 4, text: 'DI/FI Reports by Feeder and Division' },
    {
      kind: 'paragraph',
      text: 'Present the daily duration (DI) and frequency (FI) indicators for each feeder in the network. During export, the by-division report calculates the SAIDI and SAIFI indicators using an average weighted by the number of affected consumers, providing a consolidated view of supply quality in each region.',
    },
    { kind: 'heading', level: 4, text: 'Reports for the National Power Portal (NPP)' },
    {
      kind: 'paragraph',
      text: 'The system automatically generates the report used by the National Power Portal (NPP), containing the SAIDI and SAIFI indicators for each feeder, separated between planned and unplanned occurrences, in addition to information on the number and duration of failures. This report supports the consolidation and submission of corporate indicators.',
    },
    { kind: 'reportLinks', items: ['Report link'] },

    { kind: 'heading', level: 4, text: 'Complementary Supporting Reports' },
    {
      kind: 'paragraph',
      text: 'In addition to continuity indicators, the module offers operational reports that support network reliability analysis, including:',
    },
    {
      kind: 'list',
      items: [
        'Feeders with the highest number of trips.',
        'Outages lasting longer than one hour.',
        'Feeders with a high number of operations in the month.',
        'Feeders shut down for long periods.',
        'Consolidation of shutdowns by city.',
        'History of maximum and minimum voltage, current, and power values.',
        'Real-time monitoring of communication and operational health of feeders and substations.',
      ],
    },

    { kind: 'heading', level: 4, text: 'Example Report Links' },
    {
      kind: 'reportLinks',
      items: [
        'Report of 11 kV Feeders Shut Down for 1 Hour or More',
        'Report of 11 kV Feeders that Tripped 3 Times or More',
        'Summary of Rural Circle Outages',
        'Communication Status of 11 kV Feeders',
        'SAIFI and SAIDI by Feeder',
        'SAIFI and SAIDI by Circle, Division, City, and Section',
        'SAIFI and SAIDI General Report',
        'Report of Scheduled Shutdowns (LC) for 11 kV Feeders',
        'Report of Unscheduled Shutdowns for 11 kV Feeders',
        'Report of Minimum and Maximum Values for 11 kV Feeders',
      ],
    },
  ],
}
